# Generated by Django 5.2 on 2025-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
