# Generated by Django 5.2 on 2025-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_members_only',
            field=models.BooleanField(default=False, help_text='If checked, only community members can see this post'),
        ),
    ]
