# Generated by Django 5.1.6 on 2025-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='university_logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
