# Generated by Django 5.2 on 2025-04-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interesttag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestTag',
        ),
    ]
