# Generated by Django 5.1.7 on 2025-03-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_likes_alter_post_image_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinnedpost',
            options={'ordering': ['community', 'order']},
        ),
        migrations.AddField(
            model_name='pinnedpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
